# This rule is not used by the project gpu-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the gpu.yourstartup.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gpu-operator
    app.kubernetes.io/managed-by: kustomize
  name: gpujob-editor-role
rules:
- apiGroups:
  - gpu.yourstartup.com
  resources:
  - gpujobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gpu.yourstartup.com
  resources:
  - gpujobs/status
  verbs:
  - get
