---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - gpu.yourstartup.com
  resources:
  - gpujobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gpu.yourstartup.com
  resources:
  - gpujobs/finalizers
  verbs:
  - update
- apiGroups:
  - gpu.yourstartup.com
  resources:
  - gpujobs/status
  verbs:
  - get
  - patch
  - update
