apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gpujobs.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                command:
                  type: array
                  items:
                    type: string
                gpu:
                  type: integer
  scope: Namespaced
  names:
    plural: gpujobs
    singular: gpujob
    kind: GpuJob
    shortNames:
    - gj

